version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product.rule=Host(`localhost`) && (PathPrefix(`/products`) || PathPrefix(`/categories`))"
      - "traefik.http.routers.product.entrypoints=web"
      - "traefik.http.services.product.loadbalancer.server.port=5000"
    depends_on:
      - db
    ports:
      - "5001:5000"
    networks:
      - traefik_net  # Red compartida con Traefik central

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik_net

volumes:
  postgres_data:

networks:
  traefik_net:
    external: true  # Ya fue creada por traefikproxy
